### ISSUE TITLE
Amazing and why comment sort by open count options?

### ISSUE THREAD

**Issue by wangzy88** [nicholasrout/lens-launcher#8]
This is amazing!I'm using and adjusting it since I found it.Now I add a little function for me to find app by name:
![lens-launcher2016062801](https://cloud.githubusercontent.com/assets/4112268/16407536/d5de199e-3d46-11e6-82bb-22c5b160ce46.png)
I want to ask why comment sort by open count options?I think it's a useful fuction.
Thank you for share this app!

**Comment by nicholasrout** [comment]
Hi @wangzy88,

It was previously commented out because the loading of apps was too slow, and this is required after every time an app is opened (if you have sort by open count selected).

However, version 2.2.0 of the app was released recently with faster loading and sort by open count options. The update should be available on Google Play :-)
